### ISSUE TITLE
Did you use other datasets to finetune roberta?

### ISSUE THREAD

**Issue by Borororo** [kl2806/ropes-leaderboard-example#1]
Hi, thanks for sharing.
I wonder did you use any other datasets like SQuAD to pre-finetune Roberta?  Since I get quite poor results by using the target dataset: around EM56 /F1:61, and this makes sense for me by comparing it with the one written in your paper. In your paper, bert large gets F1:53 which is consistent with the powerfulness of Roberta. 
Do you mind to share your details more little bit?

**Comment by Borororo** [comment]
My bad, I was reading the old version paper put on Arkiv. I checked the newest version of the paper, I am still curious about how you could get high scores on both dev and test. Since I face a significant overfitting issue. Do you want to share your hyperparameters?

**Comment by kl2806** [comment]
Hi @Borororo, thanks for your interest! We tried to finetune on the RACE dataset (https://www.aclweb.org/anthology/D17-1082/) first and then applying it to ROPES but did not see significant performance increase from it. The hyper-parameters used are the ones used in the hugginface Transformers library for SQuaD https://github.com/huggingface/transformers/tree/master/examples.
