### ISSUE TITLE
No module named 'allennlp.models.reading_comprehension'

### ISSUE THREAD

**Issue by hansd410** [kl2806/ropes-leaderboard-example#2]
Hello
I tried to run this code, but I got an error message.
I think this code didn't follow allennlp library update.
Is this code unavailable now?

**Comment by kl2806** [comment]
Hi,
It looks like allennlp moved the reading comprehension modules out of the main library. I just pushed a `requirements.txt` file that has the commit that this entry was developed on. Thanks!
